# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_prob_list <- function(n_p_h, p0, n1, n11, n2, n21) {
    .Call(`_BNDtest_get_prob_list`, n_p_h, p0, n1, n11, n2, n21)
}

which_loc <- function(loc_i, loc_j, select_i, select_j) {
    .Call(`_BNDtest_which_loc`, loc_i, loc_j, select_i, select_j)
}

BNDtest_get_prob <- function(loc_i, loc_j, n1, n2, n_p, n_pm1, n_p_h, prob_list, twoside) {
    .Call(`_BNDtest_BNDtest_get_prob`, loc_i, loc_j, n1, n2, n_p, n_pm1, n_p_h, prob_list, twoside)
}

path_get_prob <- function(select_i, select_j, loc_des, n1, n2, n_p, n_pm1, n_p_h, prob_list, twoside, trace) {
    .Call(`_BNDtest_path_get_prob`, select_i, select_j, loc_des, n1, n2, n_p, n_pm1, n_p_h, prob_list, twoside, trace)
}

BNDtest_loop <- function(p_prob_max, p_l, p_i, p_j, k, n0, trace, select_i0, select_j0, p_prob, p_prob_indiv, n1, n2, select_i, select_j, twoside, n_p, n_pm1, n_p_h, prob_list, p0, alternative) {
    .Call(`_BNDtest_BNDtest_loop`, p_prob_max, p_l, p_i, p_j, k, n0, trace, select_i0, select_j0, p_prob, p_prob_indiv, n1, n2, select_i, select_j, twoside, n_p, n_pm1, n_p_h, prob_list, p0, alternative)
}

copy_list <- function(x, n, n_each) {
    .Call(`_BNDtest_copy_list`, x, n, n_each)
}

